### ISSUE TITLE
No copyright statement

### ISSUE THREAD

**Issue by jmallach** [raintank/met#1]
Hello,

I am very interested in packaging this module in Debian, however I am not able unless a copyright statement is added. Can you add a LICENSE or LICENSE.md file with the contents of the intended license?

Thanks for your lib!

**Comment by Dieterbe** [comment]
Hi @jmallach i just pushed the license/notice file.  But may I ask what exactly you want to package?
this is just a tiny library that is meant to be imported by golang projects (and compiled in).  It doesn't seem to make sense to package just this library (or module as you call it). Maybe I can be of better help when I understand better what your goal is.

**Comment by jmallach** [comment]
Hello!
Thanks for adding a LICENSE!

My interest in your library is via reverse dependencies of https://github.com/ctdk/goiardi, a chef server written in Go. Debian golang packages avoid using vendor/ libs, and instead we package them archive-wide to make reuse easier for other packagers.
